#!/bin/sh
#
# See https://github.com/rhysd/cargo-husky#readme
#

set -e

echo "+Run CI steps"

rustc --version
cargo --version
cargo fmt --all -- --check
cargo clippy -- -D warnings
cargo build
cargo build --no-default-features --features with-uds
cargo test
cargo test --no-default-features --features with-uds
cargo test --doc
RUSTDOCFLAGS="-D warnings" cargo doc --no-deps
